import React from 'react';
import { ChevronLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import './Page.css';

const Privacy: React.FC = () => {
    return (
        <div className="page-container container">
            <div className="page-header">
                <Link to="/" className="back-btn">
                    <ChevronLeft size={24} />
                </Link>
                <h1 className="page-title">Privacy Policy</h1>
                <div className="placeholder"></div>
            </div>

            <div className="page-content glass-panel" style={{ textAlign: 'justify' }}>
                <div style={{ marginBottom: '32px' }}>
                    <h2 style={{ fontSize: '20px', fontWeight: 'bold', marginBottom: '16px' }}>
                        Privacy Policy (AI-Powered Astrology Services)
                    </h2>
                    <p>
                        <strong>Integrated Money Matters Private Limited</strong> ("IMMPL," "We," "Us," or "Our") is the Data Fiduciary responsible for protecting your data under the Digital Personal Data Protection Act, 2023.
                    </p>
                    <p style={{ marginTop: '8px' }}><strong>Effective Date:</strong> December 2024</p>
                    <p><strong>Last Updated:</strong> December 2024</p>
                </div>

                <section>
                    <h2>1. Introduction and AI Transparency</h2>
                    <p>This policy describes how we collect, use, process, and safeguard your Personal Data when you use our services (the "Services").</p>
                    <p style={{ fontWeight: 'bold', marginTop: '12px' }}>Crucial Notice:</p>
                    <p>By using our Services, you acknowledge that all astrological predictions, reports, and consultation responses are generated by Artificial Intelligence (AI) models, which include proprietary algorithms developed by IMMPL and licensed third-party AI models (the "Data Processors").</p>
                </section>

                <section>
                    <h2>2. Data We Collect and Purpose of Processing</h2>
                    <p>We only collect data essential for providing personalized astrological services.</p>

                    <div style={{ overflowX: 'auto', marginTop: '16px' }}>
                        <table style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid var(--border)' }}>
                            <thead>
                                <tr style={{ background: 'var(--background-card)' }}>
                                    <th style={{ padding: '12px', border: '1px solid var(--border)', textAlign: 'left' }}>Data Category</th>
                                    <th style={{ padding: '12px', border: '1px solid var(--border)', textAlign: 'left' }}>Specific Data Points</th>
                                    <th style={{ padding: '12px', border: '1px solid var(--border)', textAlign: 'left' }}>Purpose of Processing</th>
                                    <th style={{ padding: '12px', border: '1px solid var(--border)', textAlign: 'left' }}>Lawful Basis (DPDP Act)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}><strong>A. Core Astrological Data</strong></td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Full Name, Gender, Date of Birth, Time of Birth, Place of Birth.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Essential for AI Calculation. Processed to generate your unique birth chart (Kundli) and provide accurate predictions.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Consent (Clear Affirmative Action)</td>
                                </tr>
                                <tr>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}><strong>B. Consultation/Query Data</strong></td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Text, voice, or image inputs provided when asking the AI a question (e.g., "Will my career change?").</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>AI Input for Response Generation. Processed by our AI system (including third-party models) to formulate a personalized answer.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Consent</td>
                                </tr>
                                <tr>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}><strong>C. Account & Contact Data</strong></td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Email, Phone, Encrypted Password, Billing Details.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Account creation, service delivery, payment processing, and security.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Contractual Necessity</td>
                                </tr>
                                <tr>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}><strong>D. Usage & Technical Data</strong></td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>IP Address, Device ID, User Feedback, Interaction Patterns.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Used for service improvement, security maintenance, and anonymized AI Model Enhancement.</td>
                                    <td style={{ padding: '12px', border: '1px solid var(--border)' }}>Legitimate Use/Consent</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </section>

                <section>
                    <h2>3. Use of Third-Party AI Models and Data Sharing</h2>
                    <h3>3.1. Disclosure of Third-Party Processing</h3>
                    <p>We utilize third-party AI models (Data Processors) to perform complex analysis and generate sophisticated astrological responses. Your Core Astrological Data and Consultation/Query Data are securely transferred to these third-party systems only for the purpose of generating your requested prediction.</p>

                    <h3>3.2. Data Minimisation and Confidentiality</h3>
                    <p>Before transferring data to any third-party AI provider, we apply techniques to strip or mask all direct identifiers (Name, Email, Phone Number) from the query text, wherever technically feasible.</p>
                    <p>We strictly prohibit these third parties from using your data for their own independent advertising or model training purposes, except under conditions of aggregation and anonymization.</p>

                    <h3>3.3. Cross-Border Data Transfer</h3>
                    <p>The servers and infrastructure used by these Third-Party AI providers may be located outside of India (e.g., in the United States or the European Union).</p>
                    <p>By consenting to this policy, you explicitly agree to the transfer of your data to such jurisdictions. We require our Data Processors to maintain data protection standards comparable to those mandated by the DPDP Act.</p>
                </section>

                <section>
                    <h2>4. Your Rights as a Data Principal (DPDP Act)</h2>
                    <p>You maintain full control over your Personal Data:</p>
                    <ul>
                        <li><strong>Right to Access:</strong> You may request a summary of the personal data we process about you.</li>
                        <li><strong>Right to Correction & Completion:</strong> You have the right to update or correct any inaccurate or incomplete data (e.g., correcting your Birth Time).</li>
                        <li><strong>Right of Erasure/Withdrawal of Consent:</strong> You have the right to withdraw your consent at any time. Withdrawal of consent will result in the immediate cessation of processing and the deletion of your account and associated data, subject to any legal retention requirements. The mechanism for withdrawal will be as easy as the mechanism for giving consent.</li>
                        <li><strong>Right to Grievance Redressal:</strong> You have the right to approach our Grievance Officer with any concerns.</li>
                    </ul>
                </section>

                <section>
                    <h2>5. Data Security and Retention</h2>
                    <p><strong>Security Safeguards:</strong> We implement industry-standard technical and organizational security measures, including SSL/TLS encryption for data in transit and encryption at rest, to protect your data from unauthorized access or misuse.</p>
                    <p><strong>Retention:</strong> We retain your Personal Data only for the duration necessary to fulfill the services or as required by Indian law. We will provide a 48-hour prior notice before data erasure due to account inactivity.</p>
                </section>

                <section>
                    <h2>6. Processing Personal Data of a Child (Under 18)</h2>

                    <h3>6.1. General Age Restriction</h3>
                    <p>Our Services are intended exclusively for adults (individuals aged 18 and above). We do not permit any individual under the age of 18 (a "Child") to create an account or use the Services independently.</p>

                    <h3>6.2. Processing Data of a Child for Astrological Readings</h3>
                    <p>We acknowledge that adult users (parents/lawful guardians) may wish to obtain astrological readings for their children. In such cases, the processing of the Child's Personal Data (specifically, their Core Astrological Data) will be handled under the following strict conditions, as mandated by Section 9 of the DPDP Act:</p>

                    <p><strong>A. Verifiable Parental Consent</strong></p>
                    <p><strong>Warrant of Guardianship:</strong> By entering a Child’s Birth Details into our system, the adult account holder warrants that they are the parent or lawful guardian and accept full legal responsibility for providing that data.</p>
                    <p><strong>Specific Affirmation:</strong> The account holder must provide explicit, verifiable consent by ticking a dedicated affirmation box before submitting the Child's Birth Details for processing. This consent must be securely recorded and retained by IMMPL.</p>

                    <p><strong>B. Data Minimisation and Collection Restriction</strong></p>
                    <p>We will only collect the Child's Core Astrological Data (Name, Date, Time, and Place of Birth) strictly for the purpose of generating the requested report.</p>
                    <p><strong>Prohibited Collection:</strong> No other direct personal identifiers of the Child (e.g., email, phone number, photo) will be requested, stored, or processed.</p>

                    <p><strong>C. Prohibited Processing Activities</strong></p>
                    <p>We are legally prohibited and commit not to:</p>
                    <ul>
                        <li>Undertake any processing of the Child’s data that is likely to cause a detrimental effect on the Child's well-being.</li>
                        <li>Engage in tracking, behavioural monitoring, or targeted advertising directed at the Child or based on the Child's data.</li>
                        <li>Use the Child's data (even in an aggregated form) for any purpose other than generating the specific requested reading and anonymized AI model improvement.</li>
                    </ul>

                    <h3>6.3. Right to Erasure</h3>
                    <p>The parent or lawful guardian retains the Right of Erasure for the child's data at any time. Upon receiving such a request from the account holder, IMMPL will immediately cease processing and delete the Child's associated Core Astrological Data from its active and training datasets.</p>
                </section>

                <section>
                    <h2>7. Grievance Redressal and Contact Information</h2>
                    <p>If you have any questions or wish to exercise your rights, please contact our designated Grievance Officer:</p>
                    <div style={{ padding: '16px', background: 'rgba(56, 189, 248, 0.1)', borderRadius: '8px', marginTop: '16px' }}>
                        <p><strong>Grievance Officer:</strong> [Name of Grievance Officer]</p>
                        <p><strong>Designation:</strong> Chief Compliance Officer</p>
                        <p><strong>Email:</strong> contact@saarrthi.ai</p>
                        <p><strong>Address:</strong> Integrated Money Matters Private Limited</p>
                    </div>
                </section>

                <div className="last-updated">
                    Last updated: December 2024<br />
                    Version: 2.0.0
                </div>
            </div>
        </div>
    );
};

export default Privacy;
